# .readthedocs.yaml
version: 2

# Specify the OS and Python environment explicitly
build:
  commands:
    - cp -r docs/html_docs $READTHEDOCS_OUTPUT/html/
  os: ubuntu-20.04
  tools:
    python: "3.12"

# Skip the project install
python:
  install:
    - requirements: docs/requirements.txt  # Optional if you have specific doc requirements

# Set the documentation type to 'sphinx' and serve from the pre-built HTML folder
sphinx:
  builder: dirhtml  # Ensures directory-style HTML output if needed
  configuration: false  # Disables re-building Sphinx; just serves HTML files