version: 3

build:
  os: ubuntu-24.04
  tools:
    python: latest

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt

build:
  apt_packages:
    - graphviz
