# .readthedocs.yml
version: 2

# Specify the OS and Python environment explicitly
build:
  os: ubuntu-20.04  # Use a supported OS
  tools:
    python: "3.12"   # Specify the Python version

# Disable Sphinx build on Read the Docs
# Only install the project dependencies without rebuilding docs
python:
  install:
    - method: pip
      path: .