version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz

python:
  install:
    - requirements: selenium_v2/requirements.txt

sphinx:
  configuration: selenium_v2/docs/source/conf.py
