name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - master  # Deploy when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Copy HTML documentation to gh-pages
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          mkdir -p out
          cp -r docs/html_docs/* out/
          cd out
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy documentation"
          git push -f origin gh-pages
